In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("models/anemia/synthetic_data_realistic_original.csv")

In [4]:
df.head()

,WBC,NEUT#,LYMPH#,ALY#,ASLY#,MONO#,EOS#,BASO#,NEUT%,LYMPH%,...,Mikrocyty,Makrocyty,NRBC#,NRBC%,PLT,PDW,MPV,PLCR,PCT,Label
0,12.509665,2.582740,0.760880,0.130517,0.000000,0.669411,0.217803,0.002259,49.943360,36.337857,...,1.056343,2.153055,0.017301,0.075661,361.370802,12.006671,8.916850,29.098284,0.264316,Anemia Hemolityczna
1,6.910630,6.032525,1.447419,0.000000,0.047754,0.000000,0.152524,0.041919,57.068648,29.843956,...,0.647989,0.000000,0.018124,0.000000,250.517060,15.442071,8.220022,44.147809,0.192841,Trombocytopenia
2,7.922858,6.603139,1.951306,0.084319,0.024396,0.701116,0.241729,0.048173,62.366798,24.396971,...,4.263521,2.873285,0.000000,0.182157,584.573645,12.271196,9.581002,31.541530,0.257567,Anemia Mikrocytarna
3,6.969292,4.240557,1.959089,0.000000,0.016695,0.331444,0.130386,0.053954,66.353288,20.157155,...,0.152987,0.545844,0.027134,0.000000,378.028058,13.782879,10.162401,21.337585,0.200313,Anemia Normocytarna
4,1.980545,1.639358,1.886398,0.038452,0.086294,0.000000,0.000000,0.000000,55.270172,31.989248,...,2.112127,0.000000,0.038089,0.194104,0.000000,12.121342,8.725428,25.573113,0.212088,Anemia Aplastyczna

In [5]:
df.isnull().sum()

WBC          0
NEUT#        0
LYMPH#       0
ALY#         0
ASLY#        0
MONO#        0
EOS#         0
BASO#        0
NEUT%        0
LYMPH%       0
ALY%         0
ASLY%        0
MONO%        0
EOS%         0
BASO%        0
NEUT-GI      0
NEUT-RI      0
RBC          0
HGB          0
HCT          0
MCV          0
MCH          0
MCHC         0
RDW-SD       0
RDW-CV       0
Mikrocyty    0
Makrocyty    0
NRBC#        0
NRBC%        0
PLT          0
PDW          0
MPV          0
PLCR         0
PCT          0
Label        0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27496 entries, 0 to 27495
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   WBC        27496 non-null  float64
 1   NEUT#      27496 non-null  float64
 2   LYMPH#     27496 non-null  float64
 3   ALY#       27496 non-null  float64
 4   ASLY#      27496 non-null  float64
 5   MONO#      27496 non-null  float64
 6   EOS#       27496 non-null  float64
 7   BASO#      27496 non-null  float64
 8   NEUT%      27496 non-null  float64
 9   LYMPH%     27496 non-null  float64
 10  ALY%       27496 non-null  float64
 11  ASLY%      27496 non-null  float64
 12  MONO%      27496 non-null  float64
 13  EOS%       27496 non-null  float64
 14  BASO%      27496 non-null  float64
 15  NEUT-GI    27496 non-null  float64
 16  NEUT-RI    27496 non-null  float64
 17  RBC        27496 non-null  float64
 18  HGB        27496 non-null  float64
 19  HCT        27496 non-null  float64
 20  MCV        27496 non-null  float64
 21  MCH        27496 non-null  float64
 22  MCHC       27496 non-null  float64
 23  RDW-SD     27496 non-null  float64
 24  RDW-CV     27496 non-null  float64
 25  Mikrocyty  27496 non-null  float64
 26  Makrocyty  27496 non-null  float64
 27  NRBC#      27496 non-null  float64
 28  NRBC%      27496 non-null  float64
 29  PLT        27496 non-null  float64
 30  PDW        27496 non-null  float64
 31  MPV        27496 non-null  float64
 32  PLCR       27496 non-null  float64
 33  PCT        27496 non-null  float64
 34  Label      27496 non-null  object
dtypes: float64(34), object(1)
memory usage: 7.3+ MB

In [7]:
df.shape

(27496, 35)